const fs = require("fs");
const path = "C:/Users/89682/Desktop/game competition/minigame/omega/game/electron/main.ts";
let content = fs.readFileSync(path, "utf8");

// 1. Add describeScreenshot function after getActiveWindowTitle
const insertAfter = "function getActiveWindowTitle(): string {\r\n  try {\r\n    const result = execFileSync(\r\n      \"powershell.exe\",\r\n      [\r\n        \"-NoProfile\",\r\n        \"-Command\",\r\n        `& {Add-Type -Name W -Namespace A -MemberDefinition '[DllImport(\"user32.dll\")]public static extern IntPtr GetForegroundWindow();[DllImport(\"user32.dll\")]public static extern int GetWindowText(IntPtr h,System.Text.StringBuilder t,int c);';$s=New-Object System.Text.StringBuilder 256;[A.W]::GetWindowText([A.W]::GetForegroundWindow(),$s,256)|Out-Null;$s.ToString()}`\r\n      ],\r\n      { timeout: 2000, encoding: \"utf8\" }\r\n    ).trim();\r\n    return result || \"\";\r\n  } catch {\r\n    return \"\";\r\n  }\r\n}\r\n\r\nfunction parseJsonResponse";

const newFuncs = `function getActiveWindowTitle(): string {\r\n  try {\r\n    const result = execFileSync(\r\n      \"powershell.exe\",\r\n      [\r\n        \"-NoProfile\",\r\n        \"-Command\",\r\n        \`& {Add-Type -Name W -Namespace A -MemberDefinition '[DllImport("user32.dll")]public static extern IntPtr GetForegroundWindow();[DllImport("user32.dll")]public static extern int GetWindowText(IntPtr h,System.Text.StringBuilder t,int c);';$s=New-Object System.Text.StringBuilder 256;[A.W]::GetWindowText([A.W]::GetForegroundWindow(),$s,256)|Out-Null;$s.ToString()}\`\r\n      ],\r\n      { timeout: 2000, encoding: \"utf8\" }\r\n    ).trim();\r\n    return result || \"\";\r\n  } catch {\r\n    return \"\";\r\n  }\r\n}\r\n\r\n/**\r\n * 图像描述 Agent：使用 mimo-v2.5（支持视觉）识别截图内容，返回文字描述\r\n */\r\nasync function describeScreenshot(dataUrl: string): Promise<string> {\r\n  const apiKey = process.env.MIMO_API_KEY ?? process.env.OPENAI_API_KEY;\r\n  if (!apiKey) return ";\r\n  const baseUrl = (process.env.MIMO_BASE_URL ?? process.env.OPENAI_BASE_URL ?? \"https://api.xiaomimimo.com/v1\").replace(/\\/$/, \");\r\n\r\n  try {\r\n    const response = await fetch(\`\${baseUrl}/chat/completions\`, {\r\n      method: \"POST\",\r\n      headers: {\r\n        \"Content-Type\": \"application/json\",\r\n        Authorization: \`Bearer \${apiKey}\`\r\n      },\r\n      body: JSON.stringify({\r\n        model: \"mimo-v2.5\",\r\n        messages: [\r\n          {\r\n            role: \"system\",\r\n            content: \"你是一个屏幕识别助手。请用一句简短的中文描述这张截图中用户正在做什么、屏幕上有什么主要内容。不要评价，只需客观描述。如果无法识别，请说'无法识别屏幕内容'。\"\r\n          },\r\n          {\r\n            role: \"user\",\r\n            content: [\r\n              { type: \"text\", text: \"请描述这张截图\" },\r\n              { type: \"image_url\", image_url: { url: dataUrl } }\r\n            ]\r\n          }\r\n        ],\r\n        max_tokens: 150\r\n      })\r\n    });\r\n\r\n    if (!response.ok) {\r\n      console.error(\"[describeScreenshot] HTTP\", response.status);\r\n      return \";\r\n    }\r\n\r\n    const data = await response.json() as any;\r\n    const desc = data?.choices?.[0]?.message?.content?.trim();\r\n    if (desc) return desc;\r\n    return \";\r\n  } catch (e) {\r\n    console.error(\"[describeScreenshot] error:\", e);\r\n    return \";\r\n  }\r\n}\r\n\r\nfunction parseJsonResponse`;

content = content.replace(insertAfter, newFuncs);

// 2. Refactor the ai:sendMessage handler
const oldHandler = `  const screenshot = payload.includeScreenshot ? await capturePrimaryScreen().catch(() => undefined) : undefined;\r\n  // 先尝试带截图的 API 请求，失败则获取窗口标题作为文字上下文\r\n  let aiResponse = await cloudOmegaResponse(payload.text, screenshot);\r\n  if (!aiResponse && screenshot) {\r\n    console.log('[cloudOmegaResponse] failed with screenshot, getting window title as context...');\r\n    // 获取当前活动窗口标题作为文字上下文\r\n    const windowTitle = getActiveWindowTitle();\r\n    const screenContext = windowTitle\r\n      ? '用户当前正在使用：' + windowTitle\r\n      : '用户已启用屏幕识别，但无法获取具体窗口信息';\r\n    const textWithHint = payload.text + '\\n\\n[屏幕识别上下文] ' + screenContext;\r\n    aiResponse = await cloudOmegaResponse(textWithHint, undefined);\r\n  }`;

const newHandler = `  const screenshot = payload.includeScreenshot ? await capturePrimaryScreen().catch(() => undefined) : undefined;\r\n  // 图像描述 Agent：用 mimo-v2.5 识别截图内容，转为文字描述\r\n  let screenDescription = ";\r\n  if (screenshot) {\r\n    console.log('[describeScreenshot] calling vision model...');\r\n    screenDescription = await describeScreenshot(screenshot);\r\n    console.log('[describeScreenshot] result:', screenDescription?.slice(0, 100));\r\n  }\r\n\r\n  // 构造带屏幕上下文的用户输入\r\n  let enhancedText = payload.text;\r\n  if (screenDescription) {\r\n    enhancedText = payload.text + '\\n\\n[屏幕识别] 根据截图分析，' + screenDescription;\r\n  } else if (screenshot) {\r\n    // 截图已捕获但识别失败，传窗口标题\r\n    const windowTitle = getActiveWindowTitle();\r\n    if (windowTitle) {\r\n      enhancedText = payload.text + '\\n\\n[屏幕识别] 用户当前正在使用：' + windowTitle;\r\n    }\r\n  }\r\n\r\n  // 调用 Ω 主模型（mimo-v2.5-pro），不带图片仅带文字上下文\r\n  let aiResponse = await cloudOmegaResponse(enhancedText, undefined);`;

content = content.replace(oldHandler, newHandler);

fs.writeFileSync(path, content, "utf8");
console.log("Done");
